version: "3"
services:
  redis:
    image: "redis:6.2.6"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - the_bradery

  rails:
    build: .
    command: bash -c "cd /app && bundle install && bundle exec rails db:migrate && bundle exec rails db:seed ; rm tmp/pids/server.pid ; bundle exec rails s -b 0.0.0.0"
    ports:
      - '3000:3000'
    environment:
      - RAILS_ENV=development
      - REDISCLOUD_URL=redis://redis:6379
      - APP_DOMAIN=${APP_DOMAIN:-localhost:3000}
    volumes:
      - ".:/app"
    depends_on:
      - redis
    networks:
      - the_bradery
    tty: true
    stdin_open: true

networks:
  the_bradery:
    driver: bridge

volumes:
  redis:
    driver: local
